[platformio]
default_envs = custom_three

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  adafruit/Adafruit NeoPixel@^1.12.3
  bblanchon/ArduinoJson@^7.2.1
  knolleary/PubSubClient@^2.8
build_flags =
  -D LED_PIN=5
  -D MQTT_PORT=1883
  -D WIFI_SSID=\"YOUR_WIFI_NAME\"
  -D WIFI_PASSWORD=\"YOUR_WIFI_PASSWORD\"
  -D MQTT_HOST=\"192.168.1.10\"

[env:custom_three]
build_flags =
  ${env.build_flags}
  -D PIXEL_COUNT=3
  -D LOCATION_TOPIC=\"custom\"

[env:status_one]
build_flags =
  ${env.build_flags}
  -D PIXEL_COUNT=1
  -D LOCATION_TOPIC=\"status\"

